INSERT INTO NOTICE_BOARD (NTBD_CD, FILE_CD, NTBD_DIV, VIEW_CNT, TOP_YN, POST_NM, POST_CONT, POST_IN_DATE, POST_OUT_DATE, REG_DT, REG_ID, UPD_DT, UPD_ID) VALUES
    (1, 'FILE001', 'B1', 100, 'N', '공지사항 제목 1', '공지사항 내용 1', '20240101', '20241231', CURRENT_TIMESTAMP, 'user1', CURRENT_TIMESTAMP, 'user1');

INSERT INTO NOTICE_BOARD (NTBD_CD, FILE_CD, NTBD_DIV, VIEW_CNT, TOP_YN, POST_NM, POST_CONT, POST_IN_DATE, POST_OUT_DATE, REG_DT, REG_ID, UPD_DT, UPD_ID) VALUES
    (2, 'FILE002', 'B2', 50, 'Y', '중요 공지사항 제목', '중요 공지사항 내용', '20240115', '20241231', CURRENT_TIMESTAMP, 'user2', CURRENT_TIMESTAMP, 'user2');

INSERT INTO NOTICE_BOARD (NTBD_CD, FILE_CD, NTBD_DIV, VIEW_CNT, TOP_YN, POST_NM, POST_CONT, POST_IN_DATE, POST_OUT_DATE, REG_DT, REG_ID, UPD_DT, UPD_ID) VALUES
    (3, 'FILE003', 'B3', 150, 'N', '일반 공지사항 제목', '일반 공지사항 내용', '20240201', '20241231', CURRENT_TIMESTAMP, 'user3', CURRENT_TIMESTAMP, 'user3');